### ISSUE TITLE
Invalid download url for RAK packet forwader

### ISSUE THREAD

**Issue by amoat7** [chirpstack/chirpstack-docs#13]
I’m trying to configure my RAK7268 gateway. However the url for downloading the packet forwarder package is invalid. 

[Doc page](https://www.chirpstack.io/docs/chirpstack-mqtt-forwarder/install/rak.html)

**Comment by brocaar** [comment]
Thanks for reporting, there was an architecture flag change after the RAK firmware update, the above commit fixes this in the docs.
