### ISSUE TITLE
Network Server Configuration - net_id = "000000"

### ISSUE THREAD

**Issue by decyphertek-io** [chirpstack/chirpstack-docs#5]
Can you provide clarity on how to set the net_id . According to my research you are referencing class C networks and the e.g. doesnt match real world examples. Can the net_id include class A networks ? Is there is easier way to programmatically get this info via ifconfig or ip a and xxd via terminal ? Please provide feedback on the logic presented. 

[network_server]
* Class C Networks , The first three octets (24 bits / 3 bytes) represent the network ID and the last octet (8 bits /1 bytes) is the host ID.
* Example: Private IP = 172.31.26.66 ; Network ID = 172.31.26.0 ; Host ID = 0.0.0.66
* Encode as Hex - https://convertstring.com/EncodeDecode/HexEncode  = 3137322E33312E32362E30
* For Class A first octet represents network ID as the prefix of the first octet is 0, it uses the remaining 7 bits for network ID, 
* Example: Public IP = 107.23.169.36 ; Network ID = 107.0.0.0 ; Host ID = 0.23.169.36
* Encode as Hex - https://convertstring.com/EncodeDecode/HexEncode = 3130372E302E302E30
* Network identifier (NetID, 3 bytes) encoded as HEX (e.g. 010203)
net_id="000000"

Reference:
https://decyphertek.readthedocs.io/en/latest/#ChirpStack/
https://www.geeksforgeeks.org/what-is-network-id-and-host-id-in-ip-addresses/

**Comment by brocaar** [comment]
The NetID is a value that can be obtained from the LoRa Alliance, it has nothing to do with your IP address. See also: https://lora-alliance.org/resource_hub/netid-faqs/.

> 2. Do I need a NetID assigned by the LoRa Alliance?

You need to have a NetID if you are operating a LoRaWAN network and you are collaborating with the other networks (i.e., supporting roaming).

If you have a non-collaborating network, then you can use the 0x000000 or 0x000001 NetID values. These values are reserved and can be used by any LoRaWAN network that does not have an assigned NetID.
